### ISSUE TITLE
Doesn't work from utop : function `mirage_alloc_pages' is not available

### ISSUE THREAD

**Issue by talex5** [mirage/io-page#50]
```
$ docker run --rm -it ocaml/opam:debian-9_ocaml-4.04.0
$ opam install utop io-page-unix
$ utop
utop # #require "io-page-unix";;
Error: The external function `mirage_alloc_pages' is not available
utop # #require "io-page";;
Error: The external function `mirage_alloc_pages' is not available      
```

Is this supposed to work?

**Comment by talex5** [comment]
Hmm, doing `#load "io_page_unix.cma";;` works though.

**Comment by cfcs** [comment]
@talex5 thanks for the tip, doing `#load "/home/user/.opam/4.04.2+fPIC/lib/io-page-unix/io_page_unix.cma";;` now (utop can see `io_page.cma`, but not `io_page_unix.cma`)

**Comment by hannesm** [comment]
I hit this today, and this is very inconvenient - this issue seems to be present since 2.0.0 release, i.e. build-system related (that was the time when io-page started to use jbuilder).  I used `ocamlobjinfo` on io-page-unix.cma:
```
$ ocamlobjinfo io_page_unix.cma 
File io_page_unix.cma
Force custom: no
Extra C object files: -lio_page_unix_stubs
Extra C options:
Extra dynamically-loaded libraries: -lio_page_unix_stubs
Unit name: Io_page_unix_dummy
Interfaces imported:
        9b04ecdc97e5102c1d342892ef7ad9a2        Pervasives
        4ca72777394d30fdc2abbb80096a709d        Io_page_unix_dummy
        79ae8c0eb753af6b441fe05456c7970b        CamlinternalFormatBasics
Required globals:
Uses unsafe features: no
Force link: no
```

when I look into other `cma` files of libraries which define and use C symbols (such as bigstringaf), they contain another section not present in `io_page_unix.cma`:
```
Primitives declared in this module:
        %bswap_int64
```

If I understand correctly, the `io-page-unix` library contains no ml code (and thus no references to external primitives), but only the C files.  Being not an expert in either OCaml compiler nor in jbuilder/dune, is there a way to fix this really annoying issue?  Maybe the entire implementation code (ml) should be moved to the io-page-unix / io-page-xen library?

**Comment by cfcs** [comment]
I still just have this path hardcoded in a bunch of `.ocamlinit` files. Would be very nice if someone fixed it.

**Comment by sidkshatriya** [comment]
Thank you all. Using #load in the manner described above helped me resolve this.

**Comment by avsm** [comment]
I'm planning to fix this as soon as dune 1.7 is released via the new `virtual_modules` feature to support cmi linking variants

**Comment by talex5** [comment]
@avsm: the new dune is now available - do you have a patch for this?

**Comment by avsm** [comment]
I do ... will upload on Monday

**Comment by avsm** [comment]
I never specified Monday of which month :-) Draft PR in #59 now

**Comment by dinosaure** [comment]
The current state of `io-page` fix the issue when we don't use anymore the old C layout. `dune utop` works now and we are still compatible with MirageOS 3 (and 4).
